#%RAML 1.0
title: greeting-api

uses:
  greetingLib: datatypes/greetinglib.raml

/greeting:
  get:
    description: greeting
    queryParameters:
      greet:
        description: greeting
        type: greetingLib.greet
        required: false
      lang:
        description: language
        type: greetingLib.lang
        required: false
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              english: !include examples/english.raml
              spanish: !include examples/spanish.raml